const mongoose = require('mongoose');

const specificationSchema = new mongoose.Schema({
  model: { type: String, required: true },
  pvInput: {
    maxPvInputPower: String,
    pvInputOperatingVoltageRange: String,
    ratedVoltage: String,
    maxPvInputVoltage: String,
    maxOperatingPvInputCurrent: String,
    iscPvAbsoluteMaximum: String,
    mpptTrackingChannels: String,
    maxInverterBackfeedToArray: String,
  },
  dcinputbattery: {
    batteryType: String,
    ratedBatteryVoltage: String,
    batteryVoltageRange: String,
    maxContinuousCurrent: String,
    maxAcChargingCurrent: String,
  },
  gridConnectedOperation: {
    maxContinuousPower: String,
    ratedOutputVoltage: String,
    gridVoltageRange: String,
    ratedOutputFrequency: String,
    frequencyRange: String,
    ratedOutputCurrent: String,
    maxContinuousCurrent: String,
    inrushCurrent: String,
    powerFactor: String,
    maxOutputFaultCurrent: String,
    maxOutputOvercurrentProtection: String,
  },
  offGridOperation: {
    ratedInputVoltage: String,
    mainsInputVoltageRange: String,
    ratedInputFrequency: String,
    inputFrequencyRange: String,
    acOutput: {
      maxContinuousPower: String,
      ratedOutputVoltage: String,
      outputVoltageAccuracy: String,
      ratedInputFrequency: String,
      outputFrequencyAccuracy: String,
      outputWave: String,
    },
  },
  mixedOperation: {
    ratedInputVoltage: String,
    mainsInputVoltageRange: String,
    ratedInputFrequency: String,
    inputFrequencyRange: String,
    maxContinuousCurrent: String,
    acOutput: {
      maxContinuousPower: String,
      ratedVoltage: String,
      maxOutputFaultCurrent: String,
      maxOutputOvercurrentProtection: String,
      outputCurrent: String,
      maxContinuousCurrent: String,
      inrushCurrent: String,
    },
  },
  generalParameters: {
    maxConversionEfficiency: String,
    mpptTrackingEfficiency: String,
    transferTime: String,
    display: String,
    coolingMethod: String,
    communication: String,
    protectionDegree: String,
    installation: String,
  },
  protection: {
    batteryLowVoltageAlarm: String,
    batteryLowVoltageProtection: String,
    antiIslandingProtection: String,
    overloadPowerProtection: String,
    outputShortCircuitProtection: String,
    temperatureProtection: String,
  },
  environment: {
    operatingTemperature: String,
    storageTemperature: String,
    noiseLevel: String,
    elevation: String,
    humidity: String,
  },
  dimensionsAndWeight: {
    productSize: String,
    packageSize: String,
    netWeight: String,
    grossWeight: String,
  },
});

module.exports = mongoose.model('Specification', specificationSchema);

